swagger: "2.0"
info:
  description: "This is the Publisher consumer service "
  version: "1.0.0"
  title: "Swagger Publisher consumer service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "service.swagger.io"
basePath: "/v1"
tags:
- name: "Publisher"
  description: "Everything about publisher consumer service"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "service"
  description: "Access to publisher consumer service"
schemes:
- "https"
- "http"
paths:
  /publish:
    post:
      tags:
      - "Publisher"
      summary: "Add customer information in DB"
      operationId: "addCustomerInformation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer information that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Customer"
      - name: Authorization
        in: header
        description: an authorization header
        type: string
        required: true
      - name: Activity-Id
        in: header
        description: ID of the requested TaxFiling
        type: string
      - name: Application-Id
        in: header
        description: ID of the requested TaxFiling
        type: string
      
      responses:
       "400":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse" 
       "404":
          description: "Request resource not found"
       "200" :
          description: "sucessfully subscribed"
          schema:
            $ref: "#/definitions/CustomerResponse"
      security:
      - custStore_auth:
        - "write:cust"
        
securityDefinitions:
  custStore_auth:
    type: "oauth2"
    authorizationUrl: "http://custstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:cust: "adds customer in your DB"
definitions:
  Customer:
    type: "object"
    required:
    - "customerNumber"
    - "firstName"
    - "lastName"
    - "birthdate"
    - "country"
    - "countryCode"
    - "mobileNumber"
    - "email"
    - "customerStatus"
  
    properties:
      customerNumber:
        type: "string"
        maximum: 50
        example: "C000000001"
      firstName:
        type: "string"
        minimum: 10
        maximum: 50
        example: "doggie"
      lastName:
        type: "string"
        minimum: 10
        maximum: 50
        example: "doggie"  
      birthdate:
        type: string
        description: Birthdate
        example: "01-01-2020"
        format: date
        pattern: "MM-DD-YYYY"
        minLength: 0
        maxLength: 10
      country:
          type: "string"
          example: "India"
      countryCode:
        type: "string"
        minimum: 2
        maximum: 2
        example: "IN"
      mobileNumber:
        type: "string"
        minimum: 10
        maximum: 10
        example: "9849558454"
      email:
        type: "string"
        description: "email id of customer"
        example: "navin@gmail.com"
      customerStatus:
        type: "string"
        enum:
        - "Open"
        - "Close"
        - "Suspended"
        - "Restored"
      address :
          $ref: "#/definitions/Address"
  
  Address:
    type: "object"
    required:
    - "addressLine1"
    - "postalCode"
    properties:
      addressLine1:
        type: "string"
        maximum: 50
        example: "New jersey"
      addressLine2:
        type: "string"
        example: "road no1"
      street:
        type: "string"
        example: "churchil"
      postalCode:
        type: "string"
        maximum: 5
        example: "504105"
  CustomerResponse:
    type: "object"
    required:
    - "status"
    - "message"
    properties:
      status:
        type: "string"
        example: "success"
      message:
        type: "string"
        example: "Sucessfully published the customer information"
      
  ErrorResponse:
    type: "object"
    required:
    - "status"
    - "message"
    properties:
      status:
        type: "string"
        example: "Error"
      message:
        type: "string"
        example: "Error occcured during subscribing"
      error_type:
        type: "string"
        example: "InvalidRequestException"
  
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"